In [6]:
import numpy as np
import time
np.__version__


'1.14.5'

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [51]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)  # Its just a faster algorithm
toc = time.time()
print(c)
print('Vector time: ' + str((toc-tic)*1000) + "ms")

tic = time.time()
c = 0
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print('Loop time: ' + str((toc-tic)*1000) + 'ms')


250072.9477692688
Vector time: 1.4696121215820312ms
250072.94776926044
Loop time: 331.15625381469727ms


### Broadcasting in Python:
In numpy, if you have an `mxn` matric and apply an arithematic operation to it with `mx1` matrix, python will expand `mx1` to `mxn` by duplication elements and then apply arithematic operation element by element.

- Matlab alternative for this is bsxfun

In [32]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135, 99.0, 0.9]])

cal = A.sum(axis = 0) #Vertical axis
print(cal)

percentage = 100*A/cal.reshape(1,4)  # Reshape is not necessary here. But its a constant time command. So no problem
print(percentage)

[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


### Numpy/Python peculiarities


In [35]:
a = np.random.randn(5)  # Gaussian random
print(a)

[ 0.32734682  0.2744209  -0.33911644  0.10749412 -0.08074172]


In [36]:
print(a.shape) # a is neither a column nor a row vector. Its a rank 1 array

(5,)


In [37]:
print(a.T)
print(np.dot(a, a.T))
# Unexpected behaviour

[ 0.32734682  0.2744209  -0.33911644  0.10749412 -0.08074172]
0.31553694221233025


In [50]:
# Solution
a = np.random.randn(5,1)
print(a)
assert(a.shape == (5,1)), "Error Message!"   # Use sush statements


[[ 0.25532058]
 [-1.01658161]
 [ 0.27500655]
 [-0.30929254]
 [ 0.18919992]]
